### ISSUE TITLE
optimal dataset scale f measure

### ISSUE THREAD

**Issue by kimsunkyung** [brdav/atrc#3]
How can I evaluate edge detection on NYUD dataset?
If you have evaluation code, can you provide it?

Thank you.

**Comment by brdav** [comment]
Hello,
we used the third-party [SEISM](https://github.com/jponttuset/seism) repo for evaluation and don't plan to release that code. Some helper scripts are provided in [this repo](https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch). In order to make SEISM work for NYUD: 1) add/adapt corresponding file paths (e.g. in files `db_gt.m`, `db_im.m` and `db_root_dir.m`) 2) set maxDist=0.011 [here](https://github.com/jponttuset/seism/blob/6af0cad37d40f5b4cbd6ca1d3606ec13b176c351/src/scripts/eval_method.m#L33) 
Hope this helps.

**Comment by kimsunkyung** [comment]
> Hello, we used the third-party [SEISM](https://github.com/jponttuset/seism) repo for evaluation and don't plan to release that code. Some helper scripts are provided in [this repo](https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch). In order to make SEISM work for NYUD: 1) add/adapt corresponding file paths (e.g. in files `db_gt.m`, `db_im.m` and `db_root_dir.m`) 2) set maxDist=0.011 [here](https://github.com/jponttuset/seism/blob/6af0cad37d40f5b4cbd6ca1d3606ec13b176c351/src/scripts/eval_method.m#L33) Hope this helps.

Thank you!
